In [6]:
import pandas as pd
from splink import block_on
from splink import DuckDBAPI, Linker

# Load your local file
# If the CSV is in the same folder as your script, just use the name:
df = pd.read_csv("/Users/amand/Desktop/python/Splink/PATY-Batismos-csv.csv")

# Clean up any columns if needed (similar to what you did before)
df

,unique_id,n.registro,Local,Número livro,Fl.,Transcrição,ordem_na_pag,Local de Nascimento,Local do Batismo,Freguesia,...,tipo,cópia_transcrição,código_caract,usuario_atribuido,criação,tamanho_texto,tipo de reg. paroquial,proxima_pagina,códice_fonte3,Padrinho é grande senhor
0,São José_01_1LBat_SJP_096a.jpg_624,8986.0,NaN,Batismos 2,1084,Aos vinte e dois dias do mês de janeiro de mil...,NaN,NaN,NaN,sao jose,...,Batismo,Aos vinte e dois dias do mês de janeiro de mil...,NaN,tiagogil,NaN,494.0,Batismos,São José011LBat_SJP_096b.jpg,São José011LBat_SJP_096b.jpg,GRANDE SENHOR
1,São José_01_1LBat_SJP_071a.jpg_451,10036.0,NaN,Batismos 2,451,Aos tres dias do mes de janeiro de mil sete ce...,1.0,NaN,NaN,sao jose,...,Batismo,Aos tres dias do mes de janeiro de mil sete ce...,NaN,tiagogil,19/11/2012 11:17:26,530.0,Batismos,São José011LBat_SJP_071b.jpg,São José011LBat_SJP_071b.jpg,NaN
2,São José_01_1LBat_SJP_071a.jpg_452,10037.0,NaN,Batismos 2,452,Aos seis dias do mês de janeyro de mil sete ce...,2.0,NaN,NaN,sao jose,...,Batismo,Aos seis dias do mês de janeyro de mil sete ce...,NaN,tiagogil,19/11/2012 11:25:45,550.0,Batismos,São José011LBat_SJP_071b.jpg,São José011LBat_SJP_071b.jpg,NaN
3,São José_01_1LBat_SJP_071a.jpg_453,10038.0,NaN,Batismos 2,453,Aos vinte e sete dias domes dejaneyro demil se...,3.0,NaN,NaN,sao jose,...,Batismo,Aos vinte e sete dias domes dejaneyro demil se...,NaN,tiagogil,19/11/2012 11:37:01,474.0,Batismos,São José011LBat_SJP_071b.jpg,São José011LBat_SJP_071b.jpg,NaN
4,São José_01_1LBat_SJP_071b.jpg_454,10043.0,NaN,Batismos 2,454,Ao primeyro dia do mês de fevereyro de mil set...,1.0,NaN,NaN,sao jose,...,Batismo,Ao primeyro dia do mês de fevereyro de mil set...,NaN,tiagogil,19/11/2012 11:45:58,447.0,Batismos,São José011LBat_SJP_072a.jpg,São José011LBat_SJP_072a.jpg,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7376,bat_cur_08_1779_206b.png_009,NaN,NaN,NaN,NaN,NaN,9.0,NaN,NaN,curitiba,...,Batismo,NaN,NaN,tiagogil,NaN,NaN,Batismos,bat_cur_08_1779_207a.png_009,bat,NaN
7377,bat_cur_08_1779_207a.png_009,NaN,NaN,NaN,NaN,NaN,9.0,NaN,NaN,curitiba,...,Batismo,NaN,NaN,tiagogil,NaN,NaN,Batismos,bat_cur_08_1779_207b.png_009,bat,NaN
7378,bat_cur_08_1779_207b.png_009,NaN,NaN,NaN,NaN,NaN,9.0,NaN,NaN,curitiba,...,Batismo,NaN,NaN,tiagogil,NaN,NaN,Batismos,bat_cur_08_1779_208a.png_009,bat,NaN
7379,bat_cur_08_1779_208a.png_009,NaN,NaN,NaN,NaN,NaN,9.0,NaN,NaN,curitiba,...,Batismo,NaN,NaN,tiagogil,NaN,NaN,Batismos,bat_cur_08_1779_208b.png_009,bat,NaN
7380,bat_cur_08_1779_001a.png_001,12799.0,NaN,NaN,NaN,NaN,1.0,NaN,NaN,curitiba,...,Batismo,NaN,NaN,tiagogil,16/05/2018 14:24:30,NaN,Batismos,bat_cur_08_1779_001b.png_001,bat,NaN

In [7]:
df.columns

Index(['unique_id', 'n.registro', 'Local', 'Número livro', 'Fl.',
       'Transcrição', 'ordem_na_pag', 'Local de Nascimento',
       'Local do Batismo', 'Freguesia', 'Igreja_Capela_propriedade',
       'Data do batismo', 'Data do batismo com barras', 'Data do Nascimento',
       'dia_semana_bat', 'ano', 'mes', 'dia', 'Observações', 'nome_do_filho',
       'sexo', 'filho legítimo', 'Batizador', 'Padre', 'Pai', 'Mãe',
       'Padrinho', 'Madrinha', 'marido madrinha', 'esposa padrinho',
       'pai padrinho', 'mãe padrinho', 'mãe madrinha', 'pai madrinha',
       'esposa pai', 'marido mãe', 'Avô paterno', 'Avó Paterna', 'Avô Materno',
       'Avó Materna', 'senhor_filho', 'senhor_pai', 'senhor_mãe',
       'senhor_avô_pat', 'senhor_avô_mat', 'senhor_avó_mat', 'senhor_avó_pat',
       'senhor_padrinho', 'senhor_madrinha', 'todos_os_nomes', 'senhores',
       'todos_os_senhores', 'padrinhos casados?', 'Primeiro_nome_pais',
       'Primeiro_nome_padrinhos', 'Primeiro_nome_avós_mat',
       'Primeiro_nome_avós_pat', 'usuário', 'total', 'tipo',
       'cópia_transcrição', 'código_caract', 'usuario_atribuido', 'criação',
       'tamanho_texto', 'tipo de reg. paroquial', 'proxima_pagina',
       'códice_fonte3', 'Padrinho é grande senhor'],
      dtype='str')

In [9]:
display(df.head(5))

,unique_id,n.registro,Local,Número livro,Fl.,Transcrição,ordem_na_pag,Local de Nascimento,Local do Batismo,Freguesia,...,tipo,cópia_transcrição,código_caract,usuario_atribuido,criação,tamanho_texto,tipo de reg. paroquial,proxima_pagina,códice_fonte3,Padrinho é grande senhor
0,São José_01_1LBat_SJP_096a.jpg_624,8986.0,NaN,Batismos 2,1084,Aos vinte e dois dias do mês de janeiro de mil...,NaN,NaN,NaN,sao jose,...,Batismo,Aos vinte e dois dias do mês de janeiro de mil...,NaN,tiagogil,NaN,494.0,Batismos,São José011LBat_SJP_096b.jpg,São José011LBat_SJP_096b.jpg,GRANDE SENHOR
1,São José_01_1LBat_SJP_071a.jpg_451,10036.0,NaN,Batismos 2,451,Aos tres dias do mes de janeiro de mil sete ce...,1.0,NaN,NaN,sao jose,...,Batismo,Aos tres dias do mes de janeiro de mil sete ce...,NaN,tiagogil,19/11/2012 11:17:26,530.0,Batismos,São José011LBat_SJP_071b.jpg,São José011LBat_SJP_071b.jpg,NaN
2,São José_01_1LBat_SJP_071a.jpg_452,10037.0,NaN,Batismos 2,452,Aos seis dias do mês de janeyro de mil sete ce...,2.0,NaN,NaN,sao jose,...,Batismo,Aos seis dias do mês de janeyro de mil sete ce...,NaN,tiagogil,19/11/2012 11:25:45,550.0,Batismos,São José011LBat_SJP_071b.jpg,São José011LBat_SJP_071b.jpg,NaN
3,São José_01_1LBat_SJP_071a.jpg_453,10038.0,NaN,Batismos 2,453,Aos vinte e sete dias domes dejaneyro demil se...,3.0,NaN,NaN,sao jose,...,Batismo,Aos vinte e sete dias domes dejaneyro demil se...,NaN,tiagogil,19/11/2012 11:37:01,474.0,Batismos,São José011LBat_SJP_071b.jpg,São José011LBat_SJP_071b.jpg,NaN
4,São José_01_1LBat_SJP_071b.jpg_454,10043.0,NaN,Batismos 2,454,Ao primeyro dia do mês de fevereyro de mil set...,1.0,NaN,NaN,sao jose,...,Batismo,Ao primeyro dia do mês de fevereyro de mil set...,NaN,tiagogil,19/11/2012 11:45:58,447.0,Batismos,São José011LBat_SJP_072a.jpg,São José011LBat_SJP_072a.jpg,NaN

In [10]:
from splink.exploratory import completeness_chart
from splink import DuckDBAPI
db_api = DuckDBAPI()
completeness_chart(df, db_api=db_api)

alt.LayerChart(...)

In [11]:
from splink.exploratory import profile_columns

profile_columns(df, db_api=DuckDBAPI(), top_n=10, bottom_n=5)

Warning: No charts produced for "Local" as the column only contains null values.
Warning: No charts produced for "dia_semana_bat" as the column only contains null values.
Warning: No charts produced for "marido madrinha" as the column only contains null values.
Warning: No charts produced for "esposa padrinho" as the column only contains null values.
Warning: No charts produced for "pai padrinho" as the column only contains null values.
Warning: No charts produced for "mãe padrinho" as the column only contains null values.
Warning: No charts produced for "mãe madrinha" as the column only contains null values.
Warning: No charts produced for "pai madrinha" as the column only contains null values.
Warning: No charts produced for "esposa pai" as the column only contains null values.
Warning: No charts produced for "marido mãe" as the column only contains null values.
Warning: No charts produced for "senhor_avô_pat" as the column only contains null values.
Warning: No charts produced for "senhor_avô_mat" as the column only contains null values.
Warning: No charts produced for "senhor_avó_mat" as the column only contains null values.
Warning: No charts produced for "senhor_avó_pat" as the column only contains null values.
Warning: No charts produced for "padrinhos casados?" as the column only contains null values.
Warning: No charts produced for "Primeiro_nome_avós_mat" as the column only contains null values.
Warning: No charts produced for "total" as the column only contains null values.
Warning: No charts produced for "código_caract" as the column only contains null values.

alt.VConcatChart(...)

In [ ]:

from splink.blocking_analysis import count_comparisons_from_blocking_rule

db_api = DuckDBAPI()

br = block_on("Mãe", "senhor_mãe")

counts = count_comparisons_from_blocking_rule(
    table_or_tables=df,
    blocking_rule=br,
    link_type="dedupe_only",
    db_api=db_api,
)

print(counts)

                            unique_id  n.registro  Local Número livro   Fl.  \
0  São José_01_1LBat_SJP_096a.jpg_624      8986.0    NaN   Batismos 2  1084
1  São José_01_1LBat_SJP_071a.jpg_451     10036.0    NaN   Batismos 2   451
2  São José_01_1LBat_SJP_071a.jpg_452     10037.0    NaN   Batismos 2   452
3  São José_01_1LBat_SJP_071a.jpg_453     10038.0    NaN   Batismos 2   453
4  São José_01_1LBat_SJP_071b.jpg_454     10043.0    NaN   Batismos 2   454

                                         Transcrição  ordem_na_pag  \
0  Aos vinte e dois dias do mês de janeiro de mil...           NaN
1  Aos tres dias do mes de janeiro de mil sete ce...           1.0
2  Aos seis dias do mês de janeyro de mil sete ce...           2.0
3  Aos vinte e sete dias domes dejaneyro demil se...           3.0
4  Ao primeyro dia do mês de fevereyro de mil set...           1.0

  Local de Nascimento Local do Batismo Freguesia  ...     tipo  \
0                 NaN              NaN  sao jose  ...  Batismo
1                 NaN              NaN  sao jose  ...  Batismo
2                 NaN              NaN  sao jose  ...  Batismo
3                 NaN              NaN  sao jose  ...  Batismo
4                 NaN              NaN  sao jose  ...  Batismo

                                   cópia_transcrição código_caract  \
0  Aos vinte e dois dias do mês de janeiro de mil...           NaN
1  Aos tres dias do mes de janeiro de mil sete ce...           NaN
2  Aos seis dias do mês de janeyro de mil sete ce...           NaN
3  Aos vinte e sete dias domes dejaneyro demil se...           NaN
4  Ao primeyro dia do mês de fevereyro de mil set...           NaN

  usuario_atribuido              criação tamanho_texto tipo de reg. paroquial  \
0          tiagogil                  NaN         494.0               Batismos
1          tiagogil  19/11/2012 11:17:26         530.0               Batismos
2          tiagogil  19/11/2012 11:25:45         550.0               Batismos
3          tiagogil  19/11/2012 11:37:01         474.0               Batismos
4          tiagogil  19/11/2012 11:45:58         447.0               Batismos

                 proxima_pagina                 códice_fonte3  \
0  São José011LBat_SJP_096b.jpg  São José011LBat_SJP_096b.jpg
1  São José011LBat_SJP_071b.jpg  São José011LBat_SJP_071b.jpg
2  São José011LBat_SJP_071b.jpg  São José011LBat_SJP_071b.jpg
3  São José011LBat_SJP_071b.jpg  São José011LBat_SJP_071b.jpg
4  São José011LBat_SJP_072a.jpg  São José011LBat_SJP_072a.jpg

  Padrinho é grande senhor
0            GRANDE SENHOR
1                      NaN
2                      NaN
3                      NaN
4                      NaN

[5 rows x 69 columns]
{'number_of_comparisons_generated_pre_filter_conditions': 1287, 'number_of_comparisons_to_be_scored_post_filter_conditions': 322, 'filter_conditions_identified': '', 'equi_join_conditions_identified': 'l."Mãe" = r."Mãe" AND l."senhor_mãe" = r."senhor_mãe"', 'link_type_join_condition': 'where l."unique_id" < r."unique_id"'}

In [5]:
from splink.blocking_analysis import n_largest_blocks

result = n_largest_blocks(table_or_tables=df,
    blocking_rule= block_on("Mãe", "senhor_mãe"),
    link_type="dedupe_only",
    db_api=db_api,
    n_largest=10
    )

result.as_pandas_dataframe()

         key_0                        key_1  count_l  count_r  block_count
0        joana        antonio jose da silva        8        8           64
1    francisca             maria dos santos        6        6           36
2         rita        manuel bueno da rocha        6        6           36
3       teresa            manuel vaz torres        6        6           36
4        joana  antonio dos santos teixeira        5        5           25
5        maria     jose carneiro dos santos        5        5           25
6        clara     antonio de souza pereira        5        5           25
7        maria     nazario teixeira da cruz        5        5           25
8      juliana             maria dos santos        5        5           25
9  escolastica         jose dos santos rosa        4        4           16